name: "Build"

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Test
      run: go test -v ./...

    - id: generate-version
      name: Generate Version
      if: github.ref_type == 'tag'
      env:
        ref_name: "${{ github.ref_name }}"
      run: |
        echo "::set-output name=version::${ref_name#v}"

    - name: Build
      if: github.ref_type == 'tag'
      env:
        VERSION: ${{ steps.generate-version.outputs.version }}
      run: ./build-releases.sh

    - name: Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: builds/blazectl-*
